[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "ungrouped-imports"
]

[tool.black]
line-length = 80
target-verion = ['py310']
skip-string-normalization = true

[tool.isort]
py_version = 310
multi_line_output = 3
length_sort = true
split_on_trailing_comma = true
